apiVersion: apps/v1
kind: Deployment
metadata:
  name: Qr-Code_generator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Qr-Code_generator
  template:
    metadata:
      labels:
        app: Qr-Code_generator
    spec:
      containers:
        - name: iotbackend-uat
          image: swapnil257/Qr-Code_generator:latest
          ports:
            - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: Qr-Code_generator-service
spec:
  type: NodePort
  selector:
    app: Qr-Code_generator-uat
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 31103  # Choose an available port in your cluster



---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: Qr-Code_generator-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: Qr-Code_generator-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
